import esbuild from "esbuild";
import process from "process";
import fs from 'fs';
import { builtinModules } from 'node:module';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const renamePlugin = {
	name: 'rename-styles',
	setup(build) {
	  build.onEnd(() => {
		// 1. Look for the file esbuild created (main.css)
		if (fs.existsSync("main.css")) {
		  // 2. Rename it to the only name Obsidian recognizes
		  fs.renameSync("main.css", "styles.css");
		  console.log("Build finished: main.css -> styles.css");
		}
	  });
	},
  };

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/index.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: true,
	plugins: [renamePlugin], // This runs the rename logic
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
